### PR TITLE
switch to SHA-3 PoW

### PR DESCRIPTION
**Pull request by wowario**
Co-authored-by: fuwa <fuwa0529@users.noreply.github.com>

### CODE REVIEW

**Comment by wowario** [comment]
OpenSSL v1.1.1 series will be supported until 11th September 2023. We will need to eventually upgrade to [OpenSSL 3.0](https://wiki.openssl.org/index.php/OpenSSL_3.0). macOS uses LibreSSL, which apparently [does not support SHA-3](https://github.com/libressl-portable/portable/issues/455).

**Comment by jwinterm** [comment]
Just to clarify - this hashing algorithm will be distinct from both the PoW that EthClassic is switching to and the PoW that Aeon is currently using, correct? Are there any coins (MaxCoin, SmartCash, etc.) that have used this exact variant to date?

**Comment by wowario** [comment]
The hashing algorithm will be the same [EthClassic](https://github.com/ethereumclassic/ECIPs/issues/13) is forking to, `Keccak-256`, but different from Aeon, which uses [KangarooTwelve](https://keccak.team/kangarootwelve.html)

**Comment by wowario** [comment]
Correction, Ethereum's `Keccak-256` does not follow [FIPS-202](https://ethereum.stackexchange.com/questions/550/which-cryptographic-hash-function-does-ethereum-use) specifications. This proposed PoW will use the finalized NIST SHA-3-256 standard.

**Pull request merged**
